### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by lez** [vmonaco/keystroke-obfuscation#2]
Hi,

Would you mind specifying a license with your source code?
A BSD type license would be absolutely great, but it largely depends on what's your intentions with the code.
I am happy to talk about advantages / disadvantages of open source licenses.

Thanks,
Lez

**Comment by vmonaco** [comment]
BSD license added, didn't realize I left this out. Thanks.

Vinnie

**Comment by lez** [comment]
Thanks for your quick reply!
Highly appreciated.

Cheers,
Lez

**Comment by lez** [comment]
Please note, the {organization} part of the third clause must be filled in with the name of the organization involved.
Or alternatively, you may omit the third clause.

Lez

**Comment by vmonaco** [comment]
Fixed, and thanks again!

Vinnie
